version: "Tensorrt-8.6.1.6"

services:
  tensorrt-opencv:
    image: huyquang/tensorrt-opencv-ultralytics
    container_name: tensorrt-opencv-build
    network_mode: host
    command: /bin/bash -c "chmod +x /script.sh && ./script.sh"
    volumes:
      - /mnt/atin/huyquang/weights/:/weights/ # sua cai nay
      - ./script.sh:/script.sh
      - ./upload_neptune.py:/upload_neptune.py
    environment: # sua nhung cai nay
      - MODEL=last-bad-good-face-640.pt
      - CLASS_NUM=2
      - INPUT_H=640
      - INPUT_W=640
      - TYPE=s
      - NEPTUNE_MODEL=ATIN-DOIRONG
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
