version: "Tensorrt-8.6.1.6"

services:
  tensorrt-opencv:
    image: huyquang/tensorrt-opencv-ultralytics
    container_name: tensorrt-opencv-build
    network_mode: host
    command: /bin/bash -c "cat scripts/combined.sh && chmod +x /scripts/* && ./scripts/combined.sh"
    volumes:
      - /mnt/atin/huyquang/face-doirong/resources/weights/last-bad-good-face-640.pt:/weights/last-bad-good-face-640.pt
      - ./scripts:/scripts
    environment:
      - CLASS_NUM=2
      - INPUT_H=640
      - INPUT_W=640
      - TYPE=s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
